#!/bin/bash

jsonmod -p qtjsbackend.new_property -v new_value add_property.json > add_property_temp.json
if [ $? -ne 0 ]; then
    echo jsonmod failed
    exit -1
fi

should_be_empty=$(diff add_property_temp.json add_property_expect.json)
if [ $? -ne 0 ]; then
    echo Diff failed
    exit -1
fi

if [ -n "$should_be_empty" ]; then
    exit -1
fi

exit 0
