#!/bin/bash

FILE=$2
PROJECT_NAME=$1
URL=$(jsonmod -p url $FILE)
REMOTE_BRANCH=$(jsonmod -p remote_branch $FILE)
BRANCH=$(jsonmod -p branch $FILE)

if [ -z "$REMOTE_BRANCH" ]; then
    if [ -n "$BRANCH" ]; then
        REMOTE_BRANCH=$BRANCH
    else
        REMOTE_BRANCH="master"
    fi
fi
echo "git clone --progress --branch $REMOTE_BRANCH $URL --recursive $PROJECT_NAME"
git clone --progress --branch $REMOTE_BRANCH $URL --recursive $PROJECT_NAME
