#!/bin/bash

FILE=$2
REMOTE_BRANCH=$(jsonmod -p scm.remote_branch $FILE)
if [ -z "$REMOTE_BRANCH" ]; then
    REMOTE_BRANCH=$(jsonmod -p scm.branch $FILE)
fi
echo "Git correcting branch to $REMOTE_BRANCH"

git checkout $REMOTE_BRANCH
