#!/bin/bash

OUT_FILE=$1
jsonmod -p scm.type -v git -i $OUT_FILE

url=$(git config --get remote.origin.url)
if [ ! -z $url ]; then
    jsonmod -p scm.url -v $url -i $OUT_FILE
fi

branch=$(basename $(git symbolic-ref HEAD))
jsonmod -p scm.branch -v $branch -i $OUT_FILE

remote=$(git config --get "branch.$branch.remote")
if [ ! -z $remote ]; then
    jsonmod -p scm.remote -v $remote -i $OUT_FILE
fi

remote_branch=$(git config --get "branch.$branch.merge")
if [ ! -z $remote_branch ]; then
    remote_branch=$(basename $remote_branch)
    jsonmod -p scm.remote_branch -v $remote_branch -i $OUT_FILE
fi

current_head=$(git rev-parse HEAD)
jsonmod -p scm.current_head -v $current_head -i $OUT_FILE

if [ ! -z $remote ] && [ ! -z $remote_branch ]; then
    common_ancestor=$(git merge-base HEAD $remote/$remote_branch)
    jsonmod -p scm.common_ancestor -v $common_ancestor -i $OUT_FILE
fi

