#!/bin/bash

FILE=$1

build_set_head=$(jsonmod -p scm.current_head $FILE)

current_dir=$(basename $PWD)
if [ ! -z $build_set_head ]; then
    ahead=$(git rev-list $build_set_head..HEAD|wc -l)
    echo "Git repository $current_dir is $ahead commits ahead of current_buildsets specified sha"
else
    echo "No registered current head"
fi
